Keep calm and

diff --git a/gayatri-travels-web/.husky/pre-commit b/gayatri-travels-web/.husky/pre-commit
--- a/gayatri-travels-web/.husky/pre-commit
+++ b/gayatri-travels-web/.husky/pre-commit
@@ -1,3 +1,19 @@
-# .husky/pre-commit
-prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
-git update-index --again
+npm run check-lint || (
+    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+    false
+)
+
+npm run check-types || (
+    echo 'Types Check Failed. Make the required changes listed above, add changes and try to commit again.'
+    false
+)
+
+npm run check-spell || (
+    echo 'CSpell. Make the required changes listed above, add changes and try to commit again.'
+    false
+)
+
+npm run test || (
+    echo 'Tests Check Failed. Make the required changes listed above, add changes and try to commit again.'
+    false
+)
